name: Trigger Test Repository Workflow

on:
  push:
    branches: [ main, prod, qa ]
  pull_request:
    branches: [ main, prod, qa ]

jobs:
  trigger-test:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Test Repository Workflow
      run: |
        if [ "${{ github.event_name }}" == "push" ]; then
          TITLE="${{ github.event.head_commit.message }}"
        else
          TITLE="${{ github.event.pull_request.title }}"
        fi
        
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.TOKEN_PERSONAL }}" \
          -H "Content-Type: application/json" \
          -d '{
                "event_type": "run-tests",
                "client_payload": {
                  "event_name": "${{ github.event_name }} en ${{ github.ref_name }}. Titulo: '"$TITLE"'",
                  "repository": "${{ github.repository }}"
                }
              }' \
          https://api.github.com/repos/NicoARF/playwright_ts/dispatches
